global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    metrics_path: /metrics
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/hosts.json
        refresh_interval: 15s