# Generated by Django 5.2 on 2025-05-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('hostname', models.CharField(max_length=100, verbose_name='Имя хоста')),
                ('address', models.GenericIPAddressField(verbose_name='IP-Адрес')),
                ('port', models.PositiveIntegerField(verbose_name='Порт')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('DOWN', 'DOWN')], default='OK', max_length=20, verbose_name='Статус мониторинга')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
                'ordering': ['name'],
            },
        ),
    ]
