# Generated by Django 5.2 on 2025-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('DOWN', 'DOWN')], default='OK', max_length=20, null=True, verbose_name='Статус мониторинга'),
        ),
    ]
