# Generated by Django 5.2 on 2025-05-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_remove_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='enable_monitoring',
            field=models.BooleanField(default=False, verbose_name='Установить мониторинг'),
        ),
        migrations.AddField(
            model_name='service',
            name='role',
            field=models.CharField(blank=True, choices=[('mongodb', 'MongoDB'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('common', 'Common')], default='common', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='service',
            name='address',
            field=models.GenericIPAddressField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hostname',
            field=models.CharField(max_length=100, verbose_name='Hostname'),
        ),
    ]
