# Generated by Django 5.2 on 2025-05-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_service_enable_monitoring_service_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='last_is_up',
            field=models.BooleanField(blank=True, help_text='Последний известный статус: True=Up, False=Down, NULL=неизвестно', null=True),
        ),
    ]
