# Generated by Django 5.2 on 2025-05-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0005_service_last_is_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='protocol',
            field=models.CharField(choices=[('tcp', 'TCP'), ('http', 'HTTP')], default='tcp', help_text='Метод проверки: TCP-коннект или HTTP-запрос', max_length=5),
        ),
    ]
