# Generated by Django 5.2 on 2025-05-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='is_up',
            field=models.BooleanField(blank=True, null=True, verbose_name='Доступен (ping)'),
        ),
    ]
